FROM registry.fedoraproject.org/fedora-minimal:38 AS source
RUN microdnf install --assumeyes --setopt=install_weak_deps=False ipxe-bootimgs-x86 syslinux-tftpboot

FROM registry.fedoraproject.org/fedora-minimal:38

RUN microdnf install --assumeyes --setopt=install_weak_deps=False tftp-server

COPY --from=source /tftpboot/pxelinux.0 /var/lib/tftpboot/
COPY --from=source /usr/share/ipxe/ipxe.lkrn /var/lib/tftpboot/
COPY pxelinux.cfg /var/lib/tftpboot/

ENTRYPOINT [ "/sbin/in.tftpd" ]
CMD [ "--foreground", "--address", "0.0.0.0:69", "--secure", "/var/lib/tftpboot"]
