## Build an ISO image suitable for USB media to netboot from this repo's iPXE
## and Ignition configurations

.PHONY: default clean
default:
# default: netboot.iso
clean:

# netboot.iso: isolinux.cfg
## TODO: https://wiki.syslinux.org/wiki/index.php?title=ISOLINUX
